 workflow_dispatch:  # permite ejecutarlo manualmente

jobs:
  notificar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          pip install requests google-auth

      - name: Ejecutar notificaciones
        env:
          FIREBASE_PROJECT_ID:      ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          VAPID_KEY:                ${{ secrets.VAPID_KEY }}
        run: python notificar.py
